package academy.android.mymovie.utils

object Constants {
    const val BASE_URL = "https://api.themoviedb.org/3/"
    const val API_KEY = "d2f1014d730bfc7776870724b9bbea77"
    const val DEFAULT_IMAGE_URL = "https://image.tmdb.org/t/p/"
    const val DEFAULT_SIZE = "original"
    const val REQUEST_PATH = "requestPath"
    const val KEY_POPULAR = "popular"
    const val KEY_TOPRATED = "top_rated"
    const val KEY_NOWPLAYING = "now_playing"
    const val KEY_UPCOMING = "upcoming"
    const val TITLE_POPULAR = "Popular"
    const val TITLE_TOPRATED = "Top rated"
    const val TITLE_NOWPLAYING = "Now playing"
    const val KEY_BASE_URL = "base_url"
    const val KEY_BACKDROP = "backdrop_size"
    const val KEY_POSTER = "poster_size"
    const val KEY_PROFILE = "profile_size"
    const val KEY_SHARED_PREF = "config_data"
    const val TITLE_UPCOMING = "Upcoming"
    const val MOVIE_KEY = "movie"
    const val ACTOR_KEY = "actor"
    const val KEY_SEARCH = "searchText"
    const val DEFAULT_SEARCH = "Avengers"
}